# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/lib/jenkins/workspace/project-yangpai

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/lib/jenkins/workspace/project-yangpai

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/lib/jenkins/workspace/project-yangpai/CMakeFiles /var/lib/jenkins/workspace/project-yangpai//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/lib/jenkins/workspace/project-yangpai/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yangpai_service

# Build rule for target.
yangpai_service: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpai_service
.PHONY : yangpai_service

# fast build rule for target.
yangpai_service/fast:
	$(MAKE) $(MAKESILENT) -f project_frame/CMakeFiles/yangpai_service.dir/build.make project_frame/CMakeFiles/yangpai_service.dir/build
.PHONY : yangpai_service/fast

#=============================================================================
# Target rules for targets named service_mysql_proxy

# Build rule for target.
service_mysql_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_mysql_proxy
.PHONY : service_mysql_proxy

# fast build rule for target.
service_mysql_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_mysql/CMakeFiles/service_mysql_proxy.dir/build.make project_mysql/CMakeFiles/service_mysql_proxy.dir/build
.PHONY : service_mysql_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_mysql

# Build rule for target.
yangpi_service_mysql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_mysql
.PHONY : yangpi_service_mysql

# fast build rule for target.
yangpi_service_mysql/fast:
	$(MAKE) $(MAKESILENT) -f project_mysql/CMakeFiles/yangpi_service_mysql.dir/build.make project_mysql/CMakeFiles/yangpi_service_mysql.dir/build
.PHONY : yangpi_service_mysql/fast

#=============================================================================
# Target rules for targets named service_i2c_proxy

# Build rule for target.
service_i2c_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_i2c_proxy
.PHONY : service_i2c_proxy

# fast build rule for target.
service_i2c_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_i2cbus/CMakeFiles/service_i2c_proxy.dir/build.make project_i2cbus/CMakeFiles/service_i2c_proxy.dir/build
.PHONY : service_i2c_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_i2cbus

# Build rule for target.
yangpi_service_i2cbus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_i2cbus
.PHONY : yangpi_service_i2cbus

# fast build rule for target.
yangpi_service_i2cbus/fast:
	$(MAKE) $(MAKESILENT) -f project_i2cbus/CMakeFiles/yangpi_service_i2cbus.dir/build.make project_i2cbus/CMakeFiles/yangpi_service_i2cbus.dir/build
.PHONY : yangpi_service_i2cbus/fast

#=============================================================================
# Target rules for targets named service_adjust_proxy

# Build rule for target.
service_adjust_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_adjust_proxy
.PHONY : service_adjust_proxy

# fast build rule for target.
service_adjust_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_adjust/CMakeFiles/service_adjust_proxy.dir/build.make project_adjust/CMakeFiles/service_adjust_proxy.dir/build
.PHONY : service_adjust_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_adjust

# Build rule for target.
yangpi_service_adjust: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_adjust
.PHONY : yangpi_service_adjust

# fast build rule for target.
yangpi_service_adjust/fast:
	$(MAKE) $(MAKESILENT) -f project_adjust/CMakeFiles/yangpi_service_adjust.dir/build.make project_adjust/CMakeFiles/yangpi_service_adjust.dir/build
.PHONY : yangpi_service_adjust/fast

#=============================================================================
# Target rules for targets named service_pioneers_proxy

# Build rule for target.
service_pioneers_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_pioneers_proxy
.PHONY : service_pioneers_proxy

# fast build rule for target.
service_pioneers_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_pioneers/CMakeFiles/service_pioneers_proxy.dir/build.make project_pioneers/CMakeFiles/service_pioneers_proxy.dir/build
.PHONY : service_pioneers_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_pioneers

# Build rule for target.
yangpi_service_pioneers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_pioneers
.PHONY : yangpi_service_pioneers

# fast build rule for target.
yangpi_service_pioneers/fast:
	$(MAKE) $(MAKESILENT) -f project_pioneers/CMakeFiles/yangpi_service_pioneers.dir/build.make project_pioneers/CMakeFiles/yangpi_service_pioneers.dir/build
.PHONY : yangpi_service_pioneers/fast

#=============================================================================
# Target rules for targets named service_rtu_proxy

# Build rule for target.
service_rtu_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_rtu_proxy
.PHONY : service_rtu_proxy

# fast build rule for target.
service_rtu_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_freemodbus/CMakeFiles/service_rtu_proxy.dir/build.make project_freemodbus/CMakeFiles/service_rtu_proxy.dir/build
.PHONY : service_rtu_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_rtu

# Build rule for target.
yangpi_service_rtu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_rtu
.PHONY : yangpi_service_rtu

# fast build rule for target.
yangpi_service_rtu/fast:
	$(MAKE) $(MAKESILENT) -f project_freemodbus/CMakeFiles/yangpi_service_rtu.dir/build.make project_freemodbus/CMakeFiles/yangpi_service_rtu.dir/build
.PHONY : yangpi_service_rtu/fast

#=============================================================================
# Target rules for targets named service_ota_proxy

# Build rule for target.
service_ota_proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 service_ota_proxy
.PHONY : service_ota_proxy

# fast build rule for target.
service_ota_proxy/fast:
	$(MAKE) $(MAKESILENT) -f project_ota/CMakeFiles/service_ota_proxy.dir/build.make project_ota/CMakeFiles/service_ota_proxy.dir/build
.PHONY : service_ota_proxy/fast

#=============================================================================
# Target rules for targets named yangpi_service_ota

# Build rule for target.
yangpi_service_ota: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yangpi_service_ota
.PHONY : yangpi_service_ota

# fast build rule for target.
yangpi_service_ota/fast:
	$(MAKE) $(MAKESILENT) -f project_ota/CMakeFiles/yangpi_service_ota.dir/build.make project_ota/CMakeFiles/yangpi_service_ota.dir/build
.PHONY : yangpi_service_ota/fast

#=============================================================================
# Target rules for targets named i2c_2631hv

# Build rule for target.
i2c_2631hv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 i2c_2631hv
.PHONY : i2c_2631hv

# fast build rule for target.
i2c_2631hv/fast:
	$(MAKE) $(MAKESILENT) -f project_hv_tools/CMakeFiles/i2c_2631hv.dir/build.make project_hv_tools/CMakeFiles/i2c_2631hv.dir/build
.PHONY : i2c_2631hv/fast

#=============================================================================
# Target rules for targets named i2c_2631vbb

# Build rule for target.
i2c_2631vbb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 i2c_2631vbb
.PHONY : i2c_2631vbb

# fast build rule for target.
i2c_2631vbb/fast:
	$(MAKE) $(MAKESILENT) -f project_vbbr_tools/CMakeFiles/i2c_2631vbb.dir/build.make project_vbbr_tools/CMakeFiles/i2c_2631vbb.dir/build
.PHONY : i2c_2631vbb/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... i2c_2631hv"
	@echo "... i2c_2631vbb"
	@echo "... service_adjust_proxy"
	@echo "... service_i2c_proxy"
	@echo "... service_mysql_proxy"
	@echo "... service_ota_proxy"
	@echo "... service_pioneers_proxy"
	@echo "... service_rtu_proxy"
	@echo "... yangpai_service"
	@echo "... yangpi_service_adjust"
	@echo "... yangpi_service_i2cbus"
	@echo "... yangpi_service_mysql"
	@echo "... yangpi_service_ota"
	@echo "... yangpi_service_pioneers"
	@echo "... yangpi_service_rtu"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

