/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "i2cbus_base.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_i2c
{
	void (*on_signal_i2c_ad1115)(HProxy proxy, T_I2cAd1115 *zdb_T_I2cAd1115);


}tInterfaceClient_yangpi_i2c;

extern const char * const INTERFACE_NAME_yangpi_i2c;
extern tInterfaceClient_yangpi_i2c INTERFACE_CLIENT_yangpi_i2c;

void yangpi_i2c_signals(HProxy proxy, DBusMessage *message);

void yangpi_i2c_call_i2c_adjust(HProxy proxy, T_I2cAdjust *zdb_T_I2cAdjust);
void yangpi_i2c_call_i2c_oled(HProxy proxy, T_I2cOled *zdb_T_I2cOled);


#ifdef __cplusplus
}
#endif
