/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "ota_data_base.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_ota
{
	void (*on_signal_ota_download)(HProxy proxy, T_OtaDownloadInfo *zdb_T_OtaDownloadInfo);
	void (*on_signal_ota_request_day)(HProxy proxy, T_OtaBeginDay *zdb_T_OtaBeginDay);
	void (*on_signal_ota_request_appoint)(HProxy proxy, T_OtaBeginDay *zdb_T_OtaBeginDay, T_OtaEndDay *zdb_T_OtaEndDay);


}tInterfaceClient_yangpi_ota;

extern const char * const INTERFACE_NAME_yangpi_ota;
extern tInterfaceClient_yangpi_ota INTERFACE_CLIENT_yangpi_ota;

void yangpi_ota_signals(HProxy proxy, DBusMessage *message);

void yangpi_ota_call_ota_send(HProxy proxy, T_OtaSendLog *zdb_T_OtaSendLog);


#ifdef __cplusplus
}
#endif
