/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "rtu_data_base.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_rtu
{


}tInterfaceClient_yangpi_rtu;

extern const char * const INTERFACE_NAME_yangpi_rtu;
extern tInterfaceClient_yangpi_rtu INTERFACE_CLIENT_yangpi_rtu;

void yangpi_rtu_signals(HProxy proxy, DBusMessage *message);

void yangpi_rtu_call_rtu_setdata(HProxy proxy, T_RtuData *zdb_T_RtuData);


#ifdef __cplusplus
}
#endif
