/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "adjust_service_base.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_adjust
{
	void (*on_signal_adjust_result)(HProxy proxy, T_AdjustOut *zdb_T_AdjustOut);


}tInterfaceClient_yangpi_adjust;

extern const char * const INTERFACE_NAME_yangpi_adjust;
extern tInterfaceClient_yangpi_adjust INTERFACE_CLIENT_yangpi_adjust;

void yangpi_adjust_signals(HProxy proxy, DBusMessage *message);

void yangpi_adjust_call_adjust_start(HProxy proxy, T_AdjustIn *zdb_T_AdjustIn);


#ifdef __cplusplus
}
#endif
