/**********************************************************************************/
/* stub.h                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "ota_data_base.h"
#ifdef __cplusplus
extern "C" {
#endif

extern const char * const INTERFACE_NAME_yangpi_ota;

typedef struct tInterfaceStub_yangpi_ota
{
	void (*ota_send)(HStub stub, T_OtaSendLog *zdb_T_OtaSendLog);

}tInterfaceStub_yangpi_ota;

extern tInterfaceStub_yangpi_ota INTERFACE_STUB_yangpi_ota;

void yangpi_ota_methods(HStub stub, DBusMessage *message);

void yangpi_ota_signal_ota_download(HStub stub, T_OtaDownloadInfo *zdb_T_OtaDownloadInfo);
void yangpi_ota_signal_ota_request_day(HStub stub, T_OtaBeginDay *zdb_T_OtaBeginDay);
void yangpi_ota_signal_ota_request_appoint(HStub stub, T_OtaBeginDay *zdb_T_OtaBeginDay, T_OtaEndDay *zdb_T_OtaEndDay);




#ifdef __cplusplus
}
#endif
