/**********************************************************************************/
/* stub.c                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_ota_stub.h"

const char * const INTERFACE_NAME_yangpi_ota = "yangpi.ota";
tInterfaceStub_yangpi_ota INTERFACE_STUB_yangpi_ota;

	
static void yangpi_ota_method_ota_send(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_OtaSendLog zdb_T_OtaSendLog;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_OtaSendLog);


	INTERFACE_STUB_yangpi_ota.ota_send(stub, &zdb_T_OtaSendLog);
}


void yangpi_ota_methods(HStub stub, DBusMessage *message)
{
	
	if (dbus_message_has_member(message, "ota_send"))
	{
		if (NULL != INTERFACE_STUB_yangpi_ota.ota_send)
		{
			yp_dbus_request(yangpi_ota_method_ota_send,stub,message,NULL);
		}
	}
    else
	{
		fprintf(stderr, "invalid method\n");
	}

}
void yangpi_ota_signal_ota_download(HStub stub, T_OtaDownloadInfo *zdb_T_OtaDownloadInfo) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_signal_create(&msg,&arg,stub->path,"yangpi.ota","ota_download",DBUS_TYPE_ARRAY, (void *)(zdb_T_OtaDownloadInfo),sizeof(T_OtaDownloadInfo));


	yp_dbus_reply(stub,msg);
}
void yangpi_ota_signal_ota_request_day(HStub stub, T_OtaBeginDay *zdb_T_OtaBeginDay) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_signal_create(&msg,&arg,stub->path,"yangpi.ota","ota_request_day",DBUS_TYPE_ARRAY, (void *)(zdb_T_OtaBeginDay),sizeof(T_OtaBeginDay));


	yp_dbus_reply(stub,msg);
}
void yangpi_ota_signal_ota_request_appoint(HStub stub, T_OtaBeginDay *zdb_T_OtaBeginDay, T_OtaEndDay *zdb_T_OtaEndDay) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_signal_create(&msg,&arg,stub->path,"yangpi.ota","ota_request_appoint",DBUS_TYPE_ARRAY, (void *)(zdb_T_OtaBeginDay),sizeof(T_OtaBeginDay));

	yp_dbus_mes_add_arry(&arg,(void *)(zdb_T_OtaEndDay),sizeof(T_OtaEndDay));

	yp_dbus_reply(stub,msg);
}

