/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_ota_proxy.h"

tInterfaceClient_yangpi_ota INTERFACE_CLIENT_yangpi_ota;

const char * const INTERFACE_NAME_yangpi_ota = "yangpi.ota";

	
static void yangpi_ota_notification_ota_download(HProxy proxy, DBusMessage *message)
{
	DBusMessageIter arg;
	T_OtaDownloadInfo zdb_T_OtaDownloadInfo;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_OtaDownloadInfo);


	INTERFACE_CLIENT_yangpi_ota.on_signal_ota_download(proxy, &zdb_T_OtaDownloadInfo);
}
	
static void yangpi_ota_notification_ota_request_day(HProxy proxy, DBusMessage *message)
{
	DBusMessageIter arg;
	T_OtaBeginDay zdb_T_OtaBeginDay;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_OtaBeginDay);


	INTERFACE_CLIENT_yangpi_ota.on_signal_ota_request_day(proxy, &zdb_T_OtaBeginDay);
}
	
static void yangpi_ota_notification_ota_request_appoint(HProxy proxy, DBusMessage *message)
{
	DBusMessageIter arg;
	T_OtaBeginDay zdb_T_OtaBeginDay;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_OtaBeginDay);

	T_OtaEndDay zdb_T_OtaEndDay;
	yp_dbus_mes_get_next_arry(&arg, &zdb_T_OtaEndDay);


	INTERFACE_CLIENT_yangpi_ota.on_signal_ota_request_appoint(proxy, &zdb_T_OtaBeginDay, &zdb_T_OtaEndDay);
}



void yangpi_ota_signals(HProxy proxy, DBusMessage *message)
{

	if (dbus_message_has_member(message, "ota_download"))
	{
		if (NULL != INTERFACE_CLIENT_yangpi_ota.on_signal_ota_download)
		{
			yp_dbus_signal(yangpi_ota_notification_ota_download,proxy,message);
		}
	}
	else if (dbus_message_has_member(message, "ota_request_day"))
	{
		if (NULL != INTERFACE_CLIENT_yangpi_ota.on_signal_ota_request_day)
		{
			yp_dbus_signal(yangpi_ota_notification_ota_request_day,proxy,message);
		}
	}
	else if (dbus_message_has_member(message, "ota_request_appoint"))
	{
		if (NULL != INTERFACE_CLIENT_yangpi_ota.on_signal_ota_request_appoint)
		{
			yp_dbus_signal(yangpi_ota_notification_ota_request_appoint,proxy,message);
		}
	}
    else
	{
		fprintf(stderr, "invalid signal\n");
	}

}

void yangpi_ota_call_ota_send(HProxy proxy, T_OtaSendLog *zdb_T_OtaSendLog) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_method_call_create(&msg,&arg,proxy->service,proxy->path,"yangpi.ota","ota_send",DBUS_TYPE_ARRAY, (void *)(zdb_T_OtaSendLog),sizeof(T_OtaSendLog));


	yp_dbus_call(proxy, msg, NULL);
}




