/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "../include/yangpai_service.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_<<INTERFACE>>
{
<<proxy_signal_struct>>

}tInterfaceClient_<<INTERFACE>>;

extern const char * const INTERFACE_NAME_<<INTERFACE>>;
extern tInterfaceClient_<<INTERFACE>> INTERFACE_CLIENT_<<INTERFACE>>;

void <<INTERFACE>>_signals(HProxy proxy, DBusMessage *message);

<<proxy_method_struct>>

#ifdef __cplusplus
}
#endif
