/**********************************************************************************/
/* stub.c                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_i2c_stub.h"

const char * const INTERFACE_NAME_yangpi_i2c = "yangpi.i2c";
tInterfaceStub_yangpi_i2c INTERFACE_STUB_yangpi_i2c;

	
static void yangpi_i2c_method_i2c_adjust(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_I2cAdjust zdb_T_I2cAdjust;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_I2cAdjust);


	INTERFACE_STUB_yangpi_i2c.i2c_adjust(stub, &zdb_T_I2cAdjust);
}
	
static void yangpi_i2c_method_i2c_oled(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_I2cOled zdb_T_I2cOled;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_I2cOled);


	INTERFACE_STUB_yangpi_i2c.i2c_oled(stub, &zdb_T_I2cOled);
}


void yangpi_i2c_methods(HStub stub, DBusMessage *message)
{
	
	if (dbus_message_has_member(message, "i2c_adjust"))
	{
		if (NULL != INTERFACE_STUB_yangpi_i2c.i2c_adjust)
		{
			yp_dbus_request(yangpi_i2c_method_i2c_adjust,stub,message,NULL);
		}
	}
	else if (dbus_message_has_member(message, "i2c_oled"))
	{
		if (NULL != INTERFACE_STUB_yangpi_i2c.i2c_oled)
		{
			yp_dbus_request(yangpi_i2c_method_i2c_oled,stub,message,NULL);
		}
	}
    else
	{
		fprintf(stderr, "invalid method\n");
	}

}
void yangpi_i2c_signal_i2c_ad1115(HStub stub, T_I2cAd1115 *zdb_T_I2cAd1115) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_signal_create(&msg,&arg,stub->path,"yangpi.i2c","i2c_ad1115",DBUS_TYPE_ARRAY, (void *)(zdb_T_I2cAd1115),sizeof(T_I2cAd1115));


	yp_dbus_reply(stub,msg);
}

