/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_i2c_proxy.h"

tInterfaceClient_yangpi_i2c INTERFACE_CLIENT_yangpi_i2c;

const char * const INTERFACE_NAME_yangpi_i2c = "yangpi.i2c";

	
static void yangpi_i2c_notification_i2c_ad1115(HProxy proxy, DBusMessage *message)
{
	DBusMessageIter arg;
	T_I2cAd1115 zdb_T_I2cAd1115;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_I2cAd1115);


	INTERFACE_CLIENT_yangpi_i2c.on_signal_i2c_ad1115(proxy, &zdb_T_I2cAd1115);
}



void yangpi_i2c_signals(HProxy proxy, DBusMessage *message)
{

	if (dbus_message_has_member(message, "i2c_ad1115"))
	{
		if (NULL != INTERFACE_CLIENT_yangpi_i2c.on_signal_i2c_ad1115)
		{
			yp_dbus_signal(yangpi_i2c_notification_i2c_ad1115,proxy,message);
		}
	}
    else
	{
		fprintf(stderr, "invalid signal\n");
	}

}

void yangpi_i2c_call_i2c_adjust(HProxy proxy, T_I2cAdjust *zdb_T_I2cAdjust) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_method_call_create(&msg,&arg,proxy->service,proxy->path,"yangpi.i2c","i2c_adjust",DBUS_TYPE_ARRAY, (void *)(zdb_T_I2cAdjust),sizeof(T_I2cAdjust));


	yp_dbus_call(proxy, msg, NULL);
}
void yangpi_i2c_call_i2c_oled(HProxy proxy, T_I2cOled *zdb_T_I2cOled) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_method_call_create(&msg,&arg,proxy->service,proxy->path,"yangpi.i2c","i2c_oled",DBUS_TYPE_ARRAY, (void *)(zdb_T_I2cOled),sizeof(T_I2cOled));


	yp_dbus_call(proxy, msg, NULL);

}




