/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_pioneers
{


}tInterfaceClient_yangpi_pioneers;

extern const char * const INTERFACE_NAME_yangpi_pioneers;
extern tInterfaceClient_yangpi_pioneers INTERFACE_CLIENT_yangpi_pioneers;

void yangpi_pioneers_signals(HProxy proxy, DBusMessage *message);



#ifdef __cplusplus
}
#endif
