/**********************************************************************************/
/* stub.h                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const char * const INTERFACE_NAME_yangpi_pioneers;

typedef struct tInterfaceStub_yangpi_pioneers
{

}tInterfaceStub_yangpi_pioneers;

extern tInterfaceStub_yangpi_pioneers INTERFACE_STUB_yangpi_pioneers;

void yangpi_pioneers_methods(HStub stub, DBusMessage *message);





#ifdef __cplusplus
}
#endif
