/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_pioneers_proxy.h"

tInterfaceClient_yangpi_pioneers INTERFACE_CLIENT_yangpi_pioneers;

const char * const INTERFACE_NAME_yangpi_pioneers = "yangpi.pioneers";




void yangpi_pioneers_signals(HProxy proxy, DBusMessage *message)
{

	fprintf(stderr, "invalid signal\n");

}





