/**********************************************************************************/
/* stub.c                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_pioneers_stub.h"

const char * const INTERFACE_NAME_yangpi_pioneers = "yangpi.pioneers";
tInterfaceStub_yangpi_pioneers INTERFACE_STUB_yangpi_pioneers;



void yangpi_pioneers_methods(HStub stub, DBusMessage *message)
{
	fprintf(stderr, "invalid method\n");
}

