/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_adjust_proxy.h"

tInterfaceClient_yangpi_adjust INTERFACE_CLIENT_yangpi_adjust;

const char * const INTERFACE_NAME_yangpi_adjust = "yangpi.adjust";

	
static void yangpi_adjust_notification_adjust_result(HProxy proxy, DBusMessage *message)
{
	DBusMessageIter arg;
	T_AdjustOut zdb_T_AdjustOut;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_AdjustOut);


	INTERFACE_CLIENT_yangpi_adjust.on_signal_adjust_result(proxy, &zdb_T_AdjustOut);
}



void yangpi_adjust_signals(HProxy proxy, DBusMessage *message)
{

	if (dbus_message_has_member(message, "adjust_result"))
	{
		if (NULL != INTERFACE_CLIENT_yangpi_adjust.on_signal_adjust_result)
		{
			yp_dbus_signal(yangpi_adjust_notification_adjust_result,proxy,message);
		}
	}
    else
	{
		fprintf(stderr, "invalid signal\n");
	}

}

void yangpi_adjust_call_adjust_start(HProxy proxy, T_AdjustIn *zdb_T_AdjustIn) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_method_call_create(&msg,&arg,proxy->service,proxy->path,"yangpi.adjust","adjust_start",DBUS_TYPE_ARRAY, (void *)(zdb_T_AdjustIn),sizeof(T_AdjustIn));


	yp_dbus_call(proxy, msg, NULL);
}




