/**********************************************************************************/
/* stub.h                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "mysql_base.h"
#ifdef __cplusplus
extern "C" {
#endif

extern const char * const INTERFACE_NAME_yangpi_mysql;

typedef struct tInterfaceStub_yangpi_mysql
{
	void (*writelog)(HStub stub, T_Write_Mysql_Log *zdb_T_Write_Mysql_Log);
	void (*writeflow)(HStub stub, T_Write_Flow_Result *zdb_T_Write_Flow_Result);
	void (*writeES)(HStub stub, T_Write_ES *zdb_T_Write_ES);
	void (*request_all)(HStub stub);

}tInterfaceStub_yangpi_mysql;

extern tInterfaceStub_yangpi_mysql INTERFACE_STUB_yangpi_mysql;

void yangpi_mysql_methods(HStub stub, DBusMessage *message);

void yangpi_mysql_signal_incept_all(HStub stub, T_Arm_Mysql *zdb_T_Arm_Mysql, T_Fpga_Set *zdb_T_Fpga_Set, T_Flow_para *zdb_T_Flow_para);




#ifdef __cplusplus
}
#endif
