/**********************************************************************************/
/* proxy.h                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "mysql_base.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct tInterfaceClient_yangpi_mysql
{
	void (*on_signal_incept_all)(HProxy proxy, T_Arm_Mysql *zdb_T_Arm_Mysql, T_Fpga_Set *zdb_T_Fpga_Set, T_Flow_para *zdb_T_Flow_para);


}tInterfaceClient_yangpi_mysql;

extern const char * const INTERFACE_NAME_yangpi_mysql;
extern tInterfaceClient_yangpi_mysql INTERFACE_CLIENT_yangpi_mysql;

void yangpi_mysql_signals(HProxy proxy, DBusMessage *message);

void yangpi_mysql_call_writelog(HProxy proxy, T_Write_Mysql_Log *zdb_T_Write_Mysql_Log);
void yangpi_mysql_call_writeflow(HProxy proxy, T_Write_Flow_Result *zdb_T_Write_Flow_Result);
void yangpi_mysql_call_writeES(HProxy proxy, T_Write_ES *zdb_T_Write_ES);
void yangpi_mysql_call_request_all(HProxy proxy);


#ifdef __cplusplus
}
#endif
