/**********************************************************************************/
/* stub.c                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_mysql_stub.h"

const char * const INTERFACE_NAME_yangpi_mysql = "yangpi.mysql";
tInterfaceStub_yangpi_mysql INTERFACE_STUB_yangpi_mysql;

	
static void yangpi_mysql_method_writelog(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_Write_Mysql_Log zdb_T_Write_Mysql_Log;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_Write_Mysql_Log);


	INTERFACE_STUB_yangpi_mysql.writelog(stub, &zdb_T_Write_Mysql_Log);
}
	
static void yangpi_mysql_method_writeflow(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_Write_Flow_Result zdb_T_Write_Flow_Result;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_Write_Flow_Result);


	INTERFACE_STUB_yangpi_mysql.writeflow(stub, &zdb_T_Write_Flow_Result);
}
	
static void yangpi_mysql_method_writeES(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_Write_ES zdb_T_Write_ES;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_Write_ES);


	INTERFACE_STUB_yangpi_mysql.writeES(stub, &zdb_T_Write_ES);
}
	
static void yangpi_mysql_method_request_all(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	INTERFACE_STUB_yangpi_mysql.request_all(stub);
}


void yangpi_mysql_methods(HStub stub, DBusMessage *message)
{
	
	if (dbus_message_has_member(message, "writelog"))
	{
		if (NULL != INTERFACE_STUB_yangpi_mysql.writelog)
		{
			yp_dbus_request(yangpi_mysql_method_writelog,stub,message,NULL);
		}
	}
	else if (dbus_message_has_member(message, "writeflow"))
	{
		if (NULL != INTERFACE_STUB_yangpi_mysql.writeflow)
		{
			yp_dbus_request(yangpi_mysql_method_writeflow,stub,message,NULL);
		}
	}
	else if (dbus_message_has_member(message, "writeES"))
	{
		if (NULL != INTERFACE_STUB_yangpi_mysql.writeES)
		{
			yp_dbus_request(yangpi_mysql_method_writeES,stub,message,NULL);
		}
	}
	else if (dbus_message_has_member(message, "request_all"))
	{
		if (NULL != INTERFACE_STUB_yangpi_mysql.request_all)
		{
			yp_dbus_request(yangpi_mysql_method_request_all,stub,message,NULL);
		}
	}
    else
	{
		fprintf(stderr, "invalid method\n");
	}

}
void yangpi_mysql_signal_incept_all(HStub stub, T_Arm_Mysql *zdb_T_Arm_Mysql, T_Fpga_Set *zdb_T_Fpga_Set, T_Flow_para *zdb_T_Flow_para) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_signal_create(&msg,&arg,stub->path,"yangpi.mysql","incept_all",DBUS_TYPE_ARRAY, (void *)(zdb_T_Arm_Mysql),sizeof(T_Arm_Mysql));

	yp_dbus_mes_add_arry(&arg,(void *)(zdb_T_Fpga_Set),sizeof(T_Fpga_Set));
	yp_dbus_mes_add_arry(&arg,(void *)(zdb_T_Flow_para),sizeof(T_Flow_para));

	yp_dbus_reply(stub,msg);
}

