/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "<<INTERFACE>>_proxy.h"

tInterfaceClient_<<INTERFACE>> INTERFACE_CLIENT_<<INTERFACE>>;

const char * const INTERFACE_NAME_<<INTERFACE>> = "<<INTERFACE_SOURCE>>";

<<proxy_signal_select_function>>


void <<INTERFACE>>_signals(HProxy proxy, DBusMessage *message)
{

<<proxy_signal_select>>else
	{
		fprintf(stderr, "invalid signal\n");
	}

}

<<proxy_call_function>>



