/**********************************************************************************/
/* stub.c                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_rtu_stub.h"

const char * const INTERFACE_NAME_yangpi_rtu = "yangpi.rtu";
tInterfaceStub_yangpi_rtu INTERFACE_STUB_yangpi_rtu;

	
static void yangpi_rtu_method_rtu_setdata(HStub stub, DBusMessage *message, DBusMessage *reply)
{
	DBusMessageIter arg;
	T_RtuData zdb_T_RtuData;
	yp_dbus_incept_message(message,&arg,DBUS_TYPE_ARRAY, &zdb_T_RtuData);


	INTERFACE_STUB_yangpi_rtu.rtu_setdata(stub, &zdb_T_RtuData);
}


void yangpi_rtu_methods(HStub stub, DBusMessage *message)
{
	
	if (dbus_message_has_member(message, "rtu_setdata"))
	{
		if (NULL != INTERFACE_STUB_yangpi_rtu.rtu_setdata)
		{
			yp_dbus_request(yangpi_rtu_method_rtu_setdata,stub,message,NULL);
		}
	}
    else
	{
		fprintf(stderr, "invalid method\n");
	}

}

