/**********************************************************************************/
/* proxy.c                                                                        */
/* generated by panda                                                             */
/**********************************************************************************/

#include <unistd.h>
#include <stdio.h>
#include <stdlib.h> 
#include <string.h>
#include "yangpi_rtu_proxy.h"

tInterfaceClient_yangpi_rtu INTERFACE_CLIENT_yangpi_rtu;

const char * const INTERFACE_NAME_yangpi_rtu = "yangpi.rtu";


void yangpi_rtu_call_rtu_setdata(HProxy proxy, T_RtuData *zdb_T_RtuData) 
{
	DBusMessage *msg;
	DBusMessageIter arg;
	
	
	yp_dbus_method_call_create(&msg,&arg,proxy->service,proxy->path,"yangpi.rtu","rtu_setdata",DBUS_TYPE_ARRAY, (void *)(zdb_T_RtuData),sizeof(T_RtuData));


	yp_dbus_call(proxy, msg, NULL);
}




