/**********************************************************************************/
/* stub.h                                                                         */
/* generated by panda                                                             */
/**********************************************************************************/

#pragma once

#include <dbus/dbus.h>
#include "yangpai_service.h"
#include "rtu_data_base.h"
#ifdef __cplusplus
extern "C" {
#endif

extern const char * const INTERFACE_NAME_yangpi_rtu;

typedef struct tInterfaceStub_yangpi_rtu
{
	void (*rtu_setdata)(HStub stub, T_RtuData *zdb_T_RtuData);

}tInterfaceStub_yangpi_rtu;

extern tInterfaceStub_yangpi_rtu INTERFACE_STUB_yangpi_rtu;

void yangpi_rtu_methods(HStub stub, DBusMessage *message);





#ifdef __cplusplus
}
#endif
